### PR TITLE
chore: bump otel deps

### LINKED ISSUE #44: feat: compatible with opentelemetry 0.26

### PR DESCRIPTION
**Pull request by MrCroxx**
Bump otel deps to 0.26.

close #44

### CODE REVIEW

**Comment by MrCroxx** [comment]
Please hold the PR. Let me test it with foyer first. 🥰

**Comment by MrCroxx** [comment]
The nightly clippy introduced more lifetime refine rules. Let me fix them in a separated PR.

**Comment by MrCroxx** [comment]
#46

**Comment by MrCroxx** [comment]
Blocked by #46

**Comment by andylokandy** [comment]
Thank you!

**Pull request merged**
